[Interface]
# Key for CIDEA-FIX
# Bouncing = 3
# NAT-PMP (Port Forwarding) = off
# VPN Accelerator = on
PrivateKey = UEe7ZTLNFPL0C/376CgixcrHyMT4QfQlB7Q86gR8unY=
Address = 10.2.0.2/32, 2a07:b944::2:2/128
DNS = 1.1.1.1, 8.8.8.8

[Peer]
# US-FREE#99
PublicKey = 03idG1N3+mPn+n2SRqYcdFdbeUYSirXzJVnIejIv30I=
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = 149.102.242.98:51820

# Uncomment the following line (delete the # symbol) to connect to Proton VPN using IPv6.
# Endpoint = [2a02:6ea0:c10d:5486::10]:51820
PersistentKeepalive = 25